### PR TITLE
Add documentation for Store tools

### PR DESCRIPTION
**Pull request by hirunatan**
I have added a chapter explaining how to use the Store tool.

### CODE REVIEW

**Comment by watchoutfreedom** [comment]
This is great, thanks. Can you comment a bit about the useRef function ussage? Idk if I missed the info

**Comment by hirunatan** [comment]
@watchoutfreedom sure! Don't know exactly what do you want. Is this enough? Or need a more in depth explanation of what is a react hook? I think in the provided link it's explained quite well.

**Comment by watchoutfreedom** [comment]
Maybe I don't understood when it's needed to use useRef function of the store and when not. That was more my question , thank you

**Comment by watchoutfreedom** [comment]
will merge and leave changes for further discussions

**Review by watchoutfreedom — APPROVED** [review]
Great

**Pull request merged**
